cam = require("lib/gamera")
bump = require("lib/bump")
require("cam")
require("level")
require("jour")
require("world")
require("res/res_base/bois")
require("res/res_base/fer")
require("res/res_base/rubis")
require("res/res_base/uranium")
require("res/res_avancer/acier")
require("res/res_avancer/planche")
require("res/res_arme/boulet")
require("res/res_arme/energie")
require("res/res_arme/fleche")
require("batiments/res_base/bucheron")
require("batiments/res_base/mine_fer")
require("batiments/res_base/mine_rubis")
require("batiments/res_base/mine_uranium")
require("batiments/res_avancer/scierie")
require("batiments/res_avancer/forge")
require("batiments/res_arme/usine_boulet")
require("batiments/res_arme/usine_energie")
require("batiments/res_arme/usine_fleche")
require("batiments/base/base")
require("batiments/base/mur")
require("batiments/base/transporteur")
require("batiments/armes/arbalette")
require("batiments/armes/canon")
require("batiments/armes/poteau")
function love.load()
  world = bump.newWorld()
  worldLoad()
end
function love.update(dt)
end
function love.draw()
  worldDraw()
end
function love.keypressed(key)
  if key == "escape" then
    love.event.quit()
  end
end
